### PR TITLE
Added data verification documentation

### PR DESCRIPTION
**Pull request by Crozin**

### CODE REVIEW

**Comment by Crozin** [comment]
@magnuslundstedt Need your input on seamless (data) verification coverage.

**Review by JEllis72 — APPROVED** [review]

**Comment by Crozin** [comment]
@spacedsweden Not yet. Waiting for approval from legal department.

**Comment by Crozin** [comment]
@spacedsweden @alex-sberna We finally got green light to publish Data Verification (seamless) as OpenBeta. This PR should be finally merged!

I've just noted I lost access to this repo. Can't alter this PR, could I ask you to remove this part:

Currently following destinations are supported:
| Country | Networks |
| ------- | -------- |
| Malesia | TBA      |
| TBA     | TBA      |
| ...     | ...      |
| TBA     | TBA      |

Other than that it's ready to merge.

**Comment by Crozin** [comment]
@alex-sberna As I've lost access to this repo (should be fixed soon hopefully) could you please resolve those conflicts (super trivial, accept all changes that reference "seameless/data").

**Pull request merged**
