### PR TITLE
Add feedback delivery information to SMS Guide

### PR DESCRIPTION
**Pull request by thomasf147**

### CODE REVIEW

**Review by JEllis72 — APPROVED** [review]

**Comment by alex-sberna** [comment]
@thomasf147 Just checking on the status of this, and also reminding we need to make sure this change is migrated over to the new doc site as well.

**Comment by thomasf147** [comment]
@alex-sberna understood but it is not my decision on when this can go public for users, product will decide.

**Comment by alex-sberna** [comment]
I completely understand that. It looks like this method is in the swagger file on the newdocs site and also is in the copy of the sms rest guide md on the newdocs site. If this isn't public yet, should those be removed for now?

**Comment by thomasf147** [comment]
I'll let @deschong comment on that. This feature is not a problem if it goes live for customers. Still, product decides.

**Comment by deschong** [comment]
I've added it into the newdocs. We should have it inside the newdocs. As I've discussed with Thomas before, we will not publish this in the current docs for now.

**Comment by alex-sberna** [comment]
I'm just going to close this merge request then, since we won't be adding it to the old readme site.

**Pull request closed without merging**
