### PR TITLE
Remove Special Considerations.

### PR DESCRIPTION
**Pull request by aaraiz-sinch**
MMS message-subject is NOT required for XML.

### CODE REVIEW

**Comment by JEllis72** [comment]
@aaraiz-sinch - from this text below, 

Special Considerations for sendMMS
MMS message-subject is required. The message-subject parameter should not contain emoji/Unicode characters as this will cause messages to get rejected by the carrier's MMSC.

Please confirm if ONLY "MMS message-subject is required" should be removed OR, if the entire Special Considerations are should be deleted. - Thank you - Jeri

**Comment by aaraiz-sinch** [comment]
@JEllis72 Hi Jeri, message-subject is not required. So I initially wanted to only remove that bullet point, but I believe that was the only "special consideration", so instead I opted to remove the whole section instead of having an empty "special considerations" section. I am not sure how it should be formatted until there are additional special considerations.

**Comment by JEllis72** [comment]
@aaraiz-sinch - I understand what you're saying. Thank you. just to confirm, should message-subject be removed from 

<request>
    <action>sendMMS</action>
    <api-key>qTFkykO9JTfahCOqJ0V2Wf5Cg1t8iWlZ</api-key>
    <to>12399471613</to>
    <from>28444</from>
    <operator-id>31062</operator-id>
    <message-subject>The subject</message-subject>

**Comment by aaraiz-sinch** [comment]
@JEllis72 replied on #300 :)

**Comment by JEllis72** [comment]
info has been updated.

**Pull request closed without merging**
